name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: "./backend/cmd/minirag/frontend/pnpm-lock.yaml"

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build all static binaries using Makefile
        run: make static-build-all

      - name: Create Homebrew Formula
        id: brew
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          SHA256=$(shasum -a 256 bin/minirag-darwin-arm64 | awk '{print $1}')
          cat > minirag.rb <<EOF
          class Minirag < Formula
            desc "Minimalist, self-hosted, single-binary RAG"
            homepage "https://github.com/komly/minirag"
            url "https://github.com/komly/minirag/releases/download/v${VERSION}/minirag-darwin-arm64"
            version "${VERSION}"
            sha256 "${SHA256}"

            def install
              bin.install "minirag-darwin-arm64" => "minirag"
            end
          end
          EOF

      - name: Push Homebrew Formula to Tap Repo
        env:
          TAP_REPO: komly/homebrew-minirag
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://$GH_TOKEN@github.com/$TAP_REPO.git taprepo
          cd taprepo
          cp ../minirag.rb ./minirag.rb
          git add minirag.rb
          git commit -m "Update minirag.rb for $VERSION [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: minirag-binaries
          path: bin/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 